name: Resize and Upload Screenshots

on:
  push:
    branches:
      - main

jobs:
  resize_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Resize Screenshots
        run: python scripts/resize_screenshots.py

      - name: Upload Resized Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: resized-screenshots
          path: screenshots/resized/**